name: pomodoro
version: git
summary:  Command line pomodoro timer
description: |
  Command line pomodoro timer, implemented in Go.

grade: stable
confinement: strict

apps:
  pomodoro:
    command: pomodoro

parts:
  pomodoro:
    source: .
    plugin: go
    go-importpath: github.com/carlmjohnson/pomodoro
